#!/bin/bash
#
# csv dumps are generated by to_csv.py at the top-level of this project
#

MAILTO=web@bmrb.wisc.edu
ERRS=""

psql -d bmrb -U bmrb -f dictionary.sql

for i in aditcatgrp.csv \
aditenumdtl \
aditenumhdr \
aditenumtie \
aditmanoverride \
aditsupergrp \
comments \
ddltypes \
nmrcifmatch \
val_enums \
validationlinks \
validationoverrides \
val_item_tbl ; do
    psql -q -U web -d metabolomics -c "\copy $i from ${i}.csv csv header"
    if [ $? -ne 0 ] ; then ERRS="${ERRS}\npsql loading ${i}" ; fi
done

if [ ! -z "${ERRS}" ] ; then
    echo "Errors loading postgres dictionary DB" | mailx -s "BMRB DB update error" $MAILTO
    exit 1
fi
